version: 3

dotenv:
  - .env

tasks:
  go-fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...

  go-test:
    desc: "Run tests"
    cmds:
      - go test -v ./...

  tidy:
    desc: "Run gofmt and goimports"
    cmds:
      - go mod tidy

  user-build:
    desc: "Build the user service"
    cmds:
      - go build -o build/user-app cmd/user/main.go

  user-run:
    desc: "Run the user service"
    cmds:
      - go run cmd/user/main.go

  user-mocks:
    desc: "Generate mocks for user repository"
    cmds:
      - mockgen -source=internal/user/domain/user.go
        -destination=internal/user/mocks/repository_mock.go -package=mocks

  user-migrate:
    desc: "Run database migrations for user service"
    cmds:
      - migrate create -ext sql {{.CLI_ARGS}}

  category-build:
    desc: "Build the category service"
    cmds:
      - go build -o build/category-app cmd/category/main.go

  category-run:
    desc: "Run the category service"
    cmds:
      - go run cmd/category/main.go

  category-mocks:
    desc: "Generate mocks for category repository"
    cmds:
      - mockgen -source=internal/category/domain/category.go
        -destination=internal/category/mocks/repository_mock.go -package=mocks
